spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password
    url: jdbc:mysql://localhost:3306/big_event
    username: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
      #mapper配置文件
  mapper-locations: classpath:mapper/*.xml